name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, nightly]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: cargo test
        run: cargo test

      - name: cargo test (remote server)
        run: cargo test
        env:
          GLUON_TEST_REMOTE_SERVER: 1
